# baseURL = 'https://ngocbichdao.github.io/'
# languageCode = 'en-us'
# title = 'Ngoc Bich DAO'
theme = 'learn'
#=========================================
# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true
#==========================================================
[Languages]
[Languages.en]
#contentDir = 'content/en'
title = "My blog"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"
[Languages.en.menu]
[[Languages.en.menu.main]]
      name = 'About'
      url = '/about'
      weight = 1
[[Languages.en.menu.main]]
      name = 'Posts'
      url = '/posts'
      weight = 2
# Add links in left panel
[[Languages.en.menu.shortcuts]] 
name = "<i class='fab fa-linkedin-in'></i> LinkedIn"
url = "https://www.linkedin.com/in/ngoc-bich-dao/"
weight = 9

[[Languages.en.menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/ngocbichdao"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-camera'></i> Showcases"
url = "/showcase"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Hugo documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
#==========================================================
[Languages.fr]
#contentDir = 'content/fr'
title = "Mon blog"
weight = 2
languageName = "Français"
landingPageURL = "/fr"
landingPageName = "<i class='fas fa-home'></i> Accueil"
[Languages.fr.menu]
[[Languages.fr.menu.main]]
      name = 'A propos'
      url = '/about'
      weight = 1
[[Languages.fr.menu.main]]
      name = 'Articles'
      url = '/posts'
      weight = 2
# Add links in left panel
[[Languages.fr.menu.shortcuts]] 
name = "<i class='fab fa-linkedin-in'></i> LinkedIn"
url = "https://www.linkedin.com/in/ngoc-bich-dao/"
weight = 9

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Repo Github"
identifier = "ds"
url = "https://github.com/ngocbichdao"
weight = 10

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-camera'></i> Vitrines"
url = "/showcase"
weight = 11

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Documentation de Hugo"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Crédits"
url = "/credits"
weight = 30
#==========================================================
[Languages.vn]
#contentDir = 'content/vn'
title = "Ngoc Bich DAO"
weight = 3
languageName = "VietNam"
landingPageURL = "/vn"
landingPageName = "<i class='fas fa-home'></i> Trang chủ"
[Languages.vn.menu]
[[Languages.vn.menu.main]]
      name = "Giới thiệu bản thân"
      url = "/about"
      weight = 1
[[Languages.vn.menu.main]]
      name = "Nội dung"
      url = "/posts"
      weight = 2
# Add links in left panel
[[Languages.vn.menu.shortcuts]] 
name = "<i class='fab fa-linkedin-in'></i> LinkedIn"
url = "https://www.linkedin.com/in/ngoc-bich-dao/"
weight = 9

[[Languages.vn.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/ngocbichdao"
weight = 10

[[Languages.vn.menu.shortcuts]]
name = "<i class='fas fa-camera'></i> Ví dụ"
url = "/showcase"
weight = 11

[[Languages.vn.menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Tài liệu của Hugo"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.vn.menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Cảm ơn"
url = "/credits"
weight = 30
#==========================================================
[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = ""
  # Author of the site, will be used in meta information
  author = "Ngoc Bich DAO"
  # Description of the site, will be used in meta information
  description = ""
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # If set to false, a Home button will appear below the search bar on the menu.
  # It is redirecting to the landing page of the current language if specified. (Default is "/")
  disableLandingPageButton = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = true
  # If set to true, prevents Hugo from including the mermaid module if not needed (will reduce load times and traffic)
  disableMermaid = true
  # Specifies the remote location of the mermaid js
  # customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "green"
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  # custom_css = ["css/foo.css", "css/bar.css"]
  # Change the title separator. Default to "::".
  titleSeparator = "-"
[outputs]
  home = [ "HTML", "RSS", "JSON"]
#========================================