# baseURL = 'https://ngocbichdao.github.io/'
# languageCode = 'en-us'
# title = 'Ngoc Bich DAO'
# theme = 'learn'
#=========================================
# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "Ngoc Bich DAO"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"

[Languages.fr]
title = "Ngoc Bich DAO"
weight = 2
languageName = "Français"
landingPageURL = "/fr"
landingPageName = "<i class='fas fa-home'></i> Accueil"
